# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontEnd.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(994, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabViewer = QtGui.QWidget()
        self.tabViewer.setEnabled(False)
        self.tabViewer.setObjectName(_fromUtf8("tabViewer"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabViewer)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.graphicsView = ImageView(self.tabViewer)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout.addWidget(self.graphicsView)
        self.tabWidget.addTab(self.tabViewer, _fromUtf8(""))
        self.tabResults = QtGui.QWidget()
        self.tabResults.setObjectName(_fromUtf8("tabResults"))
        self.tabWidget.addTab(self.tabResults, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOperation = QtGui.QMenu(self.menubar)
        self.menuOperation.setObjectName(_fromUtf8("menuOperation"))
        self.menuPlayback = QtGui.QMenu(self.menubar)
        self.menuPlayback.setObjectName(_fromUtf8("menuPlayback"))
        self.menuApplication = QtGui.QMenu(self.menubar)
        self.menuApplication.setObjectName(_fromUtf8("menuApplication"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBar.setMovable(True)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionEqualize_Histogram = QtGui.QAction(MainWindow)
        self.actionEqualize_Histogram.setEnabled(False)
        self.actionEqualize_Histogram.setObjectName(_fromUtf8("actionEqualize_Histogram"))
        self.actionCancel_Equalize_Histogram = QtGui.QAction(MainWindow)
        self.actionCancel_Equalize_Histogram.setEnabled(False)
        self.actionCancel_Equalize_Histogram.setObjectName(_fromUtf8("actionCancel_Equalize_Histogram"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setEnabled(False)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionReplay = QtGui.QAction(MainWindow)
        self.actionReplay.setEnabled(False)
        self.actionReplay.setObjectName(_fromUtf8("actionReplay"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setEnabled(False)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionExtract_Nodules = QtGui.QAction(MainWindow)
        self.actionExtract_Nodules.setEnabled(False)
        self.actionExtract_Nodules.setObjectName(_fromUtf8("actionExtract_Nodules"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuOperation.addAction(self.actionEqualize_Histogram)
        self.menuOperation.addAction(self.actionCancel_Equalize_Histogram)
        self.menuOperation.addAction(self.actionExtract_Nodules)
        self.menuPlayback.addAction(self.actionPlay)
        self.menuPlayback.addAction(self.actionStop)
        self.menuPlayback.addAction(self.actionReplay)
        self.menuApplication.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOperation.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menuApplication.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lung Nodule Detector", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabViewer), _translate("MainWindow", "Viewer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabResults), _translate("MainWindow", "Results", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuOperation.setTitle(_translate("MainWindow", "Operation", None))
        self.menuPlayback.setTitle(_translate("MainWindow", "Playback", None))
        self.menuApplication.setTitle(_translate("MainWindow", "Application", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "ToolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open MHD File", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionEqualize_Histogram.setText(_translate("MainWindow", "Equalize Histogram", None))
        self.actionEqualize_Histogram.setStatusTip(_translate("MainWindow", "Apply Histogram Equalization on MHD File", None))
        self.actionEqualize_Histogram.setShortcut(_translate("MainWindow", "H", None))
        self.actionCancel_Equalize_Histogram.setText(_translate("MainWindow", "Cancel Equalize Histogram", None))
        self.actionCancel_Equalize_Histogram.setStatusTip(_translate("MainWindow", "Cancel Histogram Equalization Effect", None))
        self.actionCancel_Equalize_Histogram.setShortcut(_translate("MainWindow", "Ctrl+H", None))
        self.actionPlay.setText(_translate("MainWindow", "Play", None))
        self.actionPlay.setStatusTip(_translate("MainWindow", "Start Playing", None))
        self.actionPlay.setShortcut(_translate("MainWindow", "P", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionStop.setStatusTip(_translate("MainWindow", "Stop Playing", None))
        self.actionStop.setShortcut(_translate("MainWindow", "S", None))
        self.actionReplay.setText(_translate("MainWindow", "Replay", None))
        self.actionReplay.setStatusTip(_translate("MainWindow", "Replay MHD File", None))
        self.actionReplay.setShortcut(_translate("MainWindow", "R", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setStatusTip(_translate("MainWindow", "Close MHD File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Quit Application", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Esc", None))
        self.actionExtract_Nodules.setText(_translate("MainWindow", "Extract Nodules", None))
        self.actionExtract_Nodules.setShortcut(_translate("MainWindow", "Ctrl+E", None))

from pyqtgraph import ImageView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

